<a href="https://colab.research.google.com/github/IzanPereira/N-cleo-CD---Analisando-dados-com-Polars/blob/main/N%C3%BAcleo_CD_Analisando_dados_com_Polars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importando a biblioteca polars
import polars as pl

In [109]:
#Lendo a o dataset winemag-data_first150k
wine = pl.read_csv('winemag-data_first150k.csv')

In [110]:
#imprimindo a o cabeçalho
#lendo as 10 primeiras linhas

wine.head(5)

shape: (5, 11)
┌─────┬─────────┬─────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│     ┆ country ┆ description ┆ designatio ┆ … ┆ region_1   ┆ region_2   ┆ variety    ┆ winery     │
│ --- ┆ ---     ┆ ---         ┆ n          ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ i64 ┆ str     ┆ str         ┆ ---        ┆   ┆ str        ┆ str        ┆ str        ┆ str        │
│     ┆         ┆             ┆ str        ┆   ┆            ┆            ┆            ┆            │
╞═════╪═════════╪═════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0   ┆ US      ┆ This        ┆ Martha's   ┆ … ┆ Napa       ┆ Napa       ┆ Cabernet   ┆ Heitz      │
│     ┆         ┆ tremendous  ┆ Vineyard   ┆   ┆ Valley     ┆            ┆ Sauvignon  ┆            │
│     ┆         ┆ 100%        ┆            ┆   ┆            ┆            ┆            ┆            │
│     ┆         ┆ varietal …  ┆            ┆   ┆            ┆            ┆            ┆            │
│ 1   ┆ Spain   ┆ Ripe aromas ┆ Carodorum  ┆ … ┆ Toro       ┆ null       ┆ Tinta de   ┆ Bodega     │
│     ┆         ┆ of fig,     ┆ Selección  ┆   ┆            ┆            ┆ Toro       ┆ Carmen     │
│     ┆         ┆ blackberry… ┆ Especial   ┆   ┆            ┆            ┆            ┆ Rodríguez  │
│     ┆         ┆             ┆ R…         ┆   ┆            ┆            ┆            ┆            │
│ 2   ┆ US      ┆ Mac Watson  ┆ Special    ┆ … ┆ Knights    ┆ Sonoma     ┆ Sauvignon  ┆ Macauley   │
│     ┆         ┆ honors the  ┆ Selected   ┆   ┆ Valley     ┆            ┆ Blanc      ┆            │
│     ┆         ┆ memory o…   ┆ Late       ┆   ┆            ┆            ┆            ┆            │
│     ┆         ┆             ┆ Harvest    ┆   ┆            ┆            ┆            ┆            │
│ 3   ┆ US      ┆ This spent  ┆ Reserve    ┆ … ┆ Willamette ┆ Willamette ┆ Pinot Noir ┆ Ponzi      │
│     ┆         ┆ 20 months   ┆            ┆   ┆ Valley     ┆ Valley     ┆            ┆            │
│     ┆         ┆ in 30% ne…  ┆            ┆   ┆            ┆            ┆            ┆            │
│ 4   ┆ France  ┆ This is the ┆ La Brûlade ┆ … ┆ Bandol     ┆ null       ┆ Provence   ┆ Domaine de │
│     ┆         ┆ top wine    ┆            ┆   ┆            ┆            ┆ red blend  ┆ la Bégude  │
│     ┆         ┆ from La B…  ┆            ┆   ┆            ┆            ┆            ┆            │
└─────┴─────────┴─────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [111]:
wine.dtypes # imprimindo os tipos de dados que temos
            # por coluna, temos String, Inteiros, Float

[Int64,
 String,
 String,
 String,
 Int64,
 Float64,
 String,
 String,
 String,
 String,
 String]

In [17]:
wine.shape #estou imprimindo a quantidade de linhaxcoluna
#são 150930 linhas e 11 colunas

(150930, 11)

In [18]:
wine.glimpse() #outra forma de obter o formato
                #quantidade de linhas(rows) e colunas
                #tipo de cada dado do Dataset

Rows: 150930
Columns: 11
$             <i64> 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
$ country     <str> 'US', 'Spain', 'US', 'US', 'France', 'Spain', 'Spain', 'Spain', 'US', 'US'
$ description <str> 'This tremendous 100% varietal wine hails from Oakville and was aged over three years in oak. Juicy red-cherry fruit and a compelling hint of caramel greet the palate, framed by elegant, fine tannins and a subtle minty tone in the background. Balanced and rewarding from start to finish, it has years ahead of it to develop further nuance. Enjoy 2022–2030.', 'Ripe aromas of fig, blackberry and cassis are softened and sweetened by a slathering of oaky chocolate and vanilla. This is full, layered, intense and cushioned on the palate, with rich flavors of chocolaty black fruits and baking spices. A toasty, everlasting finish is heady but ideally balanced. Drink through 2023.', 'Mac Watson honors the memory of a wine once made by his mother in this tremendously delicious, balanced and complex botrytised white. Dark gold in color, it layers toasted hazelnut, pear compote and orange peel flavors, reveling in the succulence of its 122 g/L of residual sugar.', "This spent 20 months in 30% new French oak, and incorporates fruit from Ponzi's Aurora, Abetina and Madrona vineyards, among others. Aromatic, dense and toasty, it deftly blends aromas and flavors of toast, cigar box, blackberry, black cherry, coffee and graphite. Tannins are polished to a fine sheen, and frame a finish loaded with dark chocolate and espresso. Drink now through 2032.", 'This is the top wine from La Bégude, named after the highest point in the vineyard at 1200 feet. It has structure, density and considerable acidity that is still calming down. With 18 months in wood, the wine has developing an extra richness and concentration. Produced by the Tari family, formerly of Château Giscours in Margaux, it is a wine made for aging. Drink from 2020.', 'Deep, dense and pure from the opening bell, this Toro is a winner. Aromas of dark ripe black fruits are cool and moderately oaked. This feels massive on the palate but sensationally balanced. Flavors of blackberry, coffee, mocha and toasty oak finish spicy, smooth and heady. Drink this exemplary Toro through 2023.', "Slightly gritty black-fruit aromas include a sweet note of pastry along with a hint of prune. Wall-to-wall saturation ensures that all corners of one's mouth are covered. Flavors of blackberry, mocha and chocolate are highly impressive and expressive, while this settles nicely on a long finish. Drink now through 2024.", 'Lush cedary black-fruit aromas are luxe and offer notes of marzipan and vanilla. This bruiser is massive and tannic on the palate, but still lush and friendly. Chocolate is a key flavor, while baked berry and cassis flavors are hardly wallflowers. On the finish, this is tannic and deep as a sea trench. Drink this saturated black-colored Toro through 2023.', "This re-named vineyard was formerly bottled as deLancellotti. You'll find striking minerality underscoring chunky black fruits. Accents of citrus and graphite comingle, with exceptional midpalate concentration. This is a wine to cellar, though it is already quite enjoyable. Drink now through 2030.", 'The producer sources from two blocks of the vineyard for this wine—one at a high elevation, which contributes bright acidity. Crunchy cranberry, pomegranate and orange peel flavors surround silky, succulent layers of texture that present as fleshy fruit. That delicately lush flavor has considerable length.'
$ designation <str> "Martha's Vineyard", 'Carodorum Selección Especial Reserva', 'Special Selected Late Harvest', 'Reserve', 'La Brûlade', 'Numanthia', 'San Román', 'Carodorum Único Crianza', 'Silice', "Gap's Crown Vineyard"
$ points      <i64> 96, 96, 96, 96, 95, 95, 95, 95, 95, 95
$ price       <f64> 235.0, 110.0, 90.0, 65.0, 66.0, 73.0, 65.0, 110.0, 65.0, 60.0
$ province    <str> 'California', 'Northern Spain', 'California', 'Oregon', 'Provence', 'Northern Spain', 'Northern Spain', 'Northern Spain', 'Oregon', 'California'
$ region_1    <str> 'Napa Valley', 'Toro', 'Knights Valley', 'Willamette Valley', 'Bandol', 'Toro', 'Toro', 'Toro', 'Chehalem Mountains', 'Sonoma Coast'
$ region_2    <str> 'Napa', null, 'Sonoma', 'Willamette Valley', null, null, null, null, 'Willamette Valley', 'Sonoma'
$ variety     <str> 'Cabernet Sauvignon', 'Tinta de Toro', 'Sauvignon Blanc', 'Pinot Noir', 'Provence red blend', 'Tinta de Toro', 'Tinta de Toro', 'Tinta de Toro', 'Pinot Noir', 'Pinot Noir'
$ winery      <str> 'Heitz', 'Bodega Carmen Rodríguez', 'Macauley', 'Ponzi', 'Domaine de la Bégude', 'Numanthia', 'Maurodos', 'Bodega Carmen Rodríguez', 'Bergström', 'Blue Farm'

In [67]:
wine.describe() # Aqui eu imprimo as métricas básicas do dataset
                # já podemos ver a quantidade de dados por colunas na primeira linha
                # observasse que algumas colunas possuem dados em suas linhas
                # por exemplo a coluna "country" possui 150925 linha preenchida das 150930
                # indicando que pode haver dados faltantes, assim como as colunas:
                #designation, price, province, region_1, region_2
                # o null informado em algumas colunas se da pelo fato de ser string

shape: (9, 12)
┌────────────┬───────────┬─────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆           ┆ country ┆ descripti ┆ … ┆ region_1  ┆ region_2  ┆ variety   ┆ winery    │
│ ---        ┆ ---       ┆ ---     ┆ on        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64       ┆ str     ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
│            ┆           ┆         ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞════════════╪═══════════╪═════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 150930.0  ┆ 150925  ┆ 150930    ┆ … ┆ 125870    ┆ 60953     ┆ 150930    ┆ 150930    │
│ null_count ┆ 0.0       ┆ 5       ┆ 0         ┆ … ┆ 25060     ┆ 89977     ┆ 0         ┆ 0         │
│ mean       ┆ 75464.5   ┆ null    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ std        ┆ 43569.882 ┆ null    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│            ┆ 402       ┆         ┆           ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 0.0       ┆ Albania ┆ "Chremisa ┆ … ┆ Abruzzo   ┆ Californi ┆ Agiorgiti ┆ '37       │
│            ┆           ┆         ┆ ," the    ┆   ┆           ┆ a Other   ┆ ko        ┆ Cellars   │
│            ┆           ┆         ┆ ancient   ┆   ┆           ┆           ┆           ┆           │
│            ┆           ┆         ┆ name o…   ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ 37732.0   ┆ null    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%        ┆ 75465.0   ┆ null    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%        ┆ 113197.0  ┆ null    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ max        ┆ 150929.0  ┆ Uruguay ┆ “Zéro     ┆ … ┆ Zonda     ┆ Willamett ┆ Žilavka   ┆ Štoka     │
│            ┆           ┆         ┆ Dosage”   ┆   ┆ Valley    ┆ e Valley  ┆           ┆           │
│            ┆           ┆         ┆ means     ┆   ┆           ┆           ┆           ┆           │
│            ┆           ┆         ┆ just      ┆   ┆           ┆           ┆           ┆           │
│            ┆           ┆         ┆ that;…    ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴─────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [31]:
wine.null_count() # trago a quantidade de dados faltante por coluna
                  # como visto no wine.describe, confirmamos que as colunas indicadas
                  # realmente possuem dados faltantes.

shape: (1, 11)
┌─────┬─────────┬─────────────┬─────────────┬───┬──────────┬──────────┬─────────┬────────┐
│     ┆ country ┆ description ┆ designation ┆ … ┆ region_1 ┆ region_2 ┆ variety ┆ winery │
│ --- ┆ ---     ┆ ---         ┆ ---         ┆   ┆ ---      ┆ ---      ┆ ---     ┆ ---    │
│ u32 ┆ u32     ┆ u32         ┆ u32         ┆   ┆ u32      ┆ u32      ┆ u32     ┆ u32    │
╞═════╪═════════╪═════════════╪═════════════╪═══╪══════════╪══════════╪═════════╪════════╡
│ 0   ┆ 5       ┆ 0           ┆ 45735       ┆ … ┆ 25060    ┆ 89977    ┆ 0       ┆ 0      │
└─────┴─────────┴─────────────┴─────────────┴───┴──────────┴──────────┴─────────┴────────┘

In [32]:
nova_wine = wine.drop_nulls() # aqui estou instanciando um novo dataframe chamado nova_wine
                              # ja com as linha que contém dados nulos excluidos.

In [33]:
nova_wine.describe() # verificando novamente as métricas principais como describe()
                      # verificando se esta tudo certo, agora não temos mais dados nulos
                      #como pode ver em count todos os valores estão iguais
                      # com a limpeza restaram 39241 linhas

shape: (9, 12)
┌────────────┬────────────┬─────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic  ┆            ┆ country ┆ descripti ┆ … ┆ region_1  ┆ region_2  ┆ variety   ┆ winery   │
│ ---        ┆ ---        ┆ ---     ┆ on        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str        ┆ f64        ┆ str     ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
│            ┆            ┆         ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞════════════╪════════════╪═════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count      ┆ 39241.0    ┆ 39241   ┆ 39241     ┆ … ┆ 39241     ┆ 39241     ┆ 39241     ┆ 39241    │
│ null_count ┆ 0.0        ┆ 0       ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ mean       ┆ 74715.5203 ┆ null    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│            ┆ 74         ┆         ┆           ┆   ┆           ┆           ┆           ┆          │
│ std        ┆ 43469.5759 ┆ null    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│            ┆ 42         ┆         ┆           ┆   ┆           ┆           ┆           ┆          │
│ min        ┆ 0.0        ┆ US      ┆ $14 is a  ┆ … ┆ Adelaida  ┆ Californi ┆ Aglianico ┆ 10 Knots │
│            ┆            ┆         ┆ pretty    ┆   ┆ District  ┆ a Other   ┆           ┆          │
│            ┆            ┆         ┆ good      ┆   ┆           ┆           ┆           ┆          │
│            ┆            ┆         ┆ price     ┆   ┆           ┆           ┆           ┆          │
│            ┆            ┆         ┆ for…      ┆   ┆           ┆           ┆           ┆          │
│ 25%        ┆ 37218.0    ┆ null    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 50%        ┆ 74534.0    ┆ null    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 75%        ┆ 112694.0   ┆ null    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ max        ┆ 150916.0   ┆ US      ┆ “Whole    ┆ … ┆ Yountvill ┆ Willamett ┆ Zweigelt  ┆ àMaurice │
│            ┆            ┆         ┆ cluster”  ┆   ┆ e         ┆ e Valley  ┆           ┆          │
│            ┆            ┆         ┆ refers to ┆   ┆           ┆           ┆           ┆          │
│            ┆            ┆         ┆ the …     ┆   ┆           ┆           ┆           ┆          │
└────────────┴────────────┴─────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
wine['country'].unique() # aqui eu só estou verificando os valores unico

In [112]:
wine.filter(pl.col("country") == "Brazil").select(pl.col("variety").unique()) #Aqui estou só filtrando as variedades
                                                                              # que estão no Brasil um total de 8

shape: (8, 1)
┌───────────────────────────┐
│ variety                   │
│ ---                       │
│ str                       │
╞═══════════════════════════╡
│ Cabernet Sauvignon        │
│ Merlot                    │
│ Bordeaux-style Red Blend  │
│ Cabernet Sauvignon-Merlot │
│ Moscato                   │
│ Tannat                    │
│ Red Blend                 │
│ Sparkling Blend           │
└───────────────────────────┘

In [116]:
wine.filter((pl.col("country") == "Brazil") # aqui eu filtro por país(country)
                  & (pl.col("points") >= 90) # aqui eu filtro por nota(>=90)
                          & (pl.col("price") < 20)).select(pl.col("variety")) #aqui eu filtro por preço menor 20
                                                    #tudo isso selecionado a variedade
                                                    #porém como não obteve resultado devido a condição não ser satisfeita

shape: (0, 1)
┌─────────┐
│ variety │
│ ---     │
│ str     │
╞═════════╡
└─────────┘

In [117]:
wine.filter((pl.col("country") == "Brazil")
                  & (pl.col("points") >= 85)
                          & (pl.col("price") < 20)).select(pl.col("variety"))
#porém quando mudo o condição para 85 pontos, vemos que o Merlot, podemos manipular os valores para
#encontrar uma lista maior, que atenda ao requesitos

shape: (1, 1)
┌─────────┐
│ variety │
│ ---     │
│ str     │
╞═════════╡
│ Merlot  │
└─────────┘

In [160]:
Agrupamento = wine.group_by("country", maintain_order=True).all() #aqui só estou agrupando
                                                    # agora temos 49 paíse no total

In [161]:
print(Agrupamento)

shape: (49, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ country   ┆           ┆ descripti ┆ designati ┆ … ┆ region_1  ┆ region_2  ┆ variety   ┆ winery   │
│ ---       ┆ ---       ┆ on        ┆ on        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ list[i64] ┆ ---       ┆ ---       ┆   ┆ list[str] ┆ list[str] ┆ list[str] ┆ list[str │
│           ┆           ┆ list[str] ┆ list[str] ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ US        ┆ [0, 2, …  ┆ ["This    ┆ ["Martha' ┆ … ┆ ["Napa    ┆ ["Napa",  ┆ ["Caberne ┆ ["Heitz" │
│           ┆ 150916]   ┆ tremendou ┆ s Vineyar ┆   ┆ Valley",  ┆ "Sonoma", ┆ t Sauvign ┆ , "Macau │
│           ┆           ┆ s 100%    ┆ d",       ┆   ┆ "Knights  ┆ … "Napa"] ┆ on",      ┆ ley", …  │
│           ┆           ┆ varieta…  ┆ "Special… ┆   ┆ Valle…    ┆           ┆ "Sauvig…  ┆ "Schra…  │
│ Spain     ┆ [1, 5, …  ┆ ["Ripe    ┆ ["Carodor ┆ … ┆ ["Toro",  ┆ [null,    ┆ ["Tinta   ┆ ["Bodega │
│           ┆ 149993]   ┆ aromas of ┆ um        ┆   ┆ "Toro", … ┆ null, …   ┆ de Toro", ┆ Carmen   │
│           ┆           ┆ fig,      ┆ Selección ┆   ┆ "Rioja"]  ┆ null]     ┆ "Tinta de ┆ Rodrígue │
│           ┆           ┆ blackber… ┆ Especial… ┆   ┆           ┆           ┆ To…       ┆ z", "N…  │
│ France    ┆ [4, 13, … ┆ ["This is ┆ ["La      ┆ … ┆ ["Bandol" ┆ [null,    ┆ ["Provenc ┆ ["Domain │
│           ┆ 150928]   ┆ the top   ┆ Brûlade", ┆   ┆ , "Madira ┆ null, …   ┆ e red     ┆ e de la  │
│           ┆           ┆ wine from ┆ "Château  ┆   ┆ n", …     ┆ null]     ┆ blend",   ┆ Bégude", │
│           ┆           ┆ La…       ┆ Montus…   ┆   ┆ "Champ…   ┆           ┆ "Tannat…  ┆ "Vign…   │
│ Italy     ┆ [10, 32,  ┆ ["Eleganc ┆ ["Ronco   ┆ … ┆ ["Collio" ┆ [null,    ┆ ["Friulan ┆ ["Borgo  │
│           ┆ … 150929] ┆ e, comple ┆ della     ┆   ┆ ,         ┆ null, …   ┆ o", "Sang ┆ del      │
│           ┆           ┆ xity and  ┆ Chiesa",  ┆   ┆ "Brunello ┆ null]     ┆ iovese",  ┆ Tiglio", │
│           ┆           ┆ str…      ┆ "Vigna …  ┆   ┆ di        ┆           ┆ … "…      ┆ "Abbadia │
│           ┆           ┆           ┆           ┆   ┆ Montal…   ┆           ┆           ┆ …        │
│ New       ┆ [25, 305, ┆ ["Yields  ┆ ["Maté's  ┆ … ┆ [null,    ┆ [null,    ┆ ["Chardon ┆ ["Kumeu  │
│ Zealand   ┆ … 150389] ┆ were down ┆ Vineyard" ┆   ┆ null, …   ┆ null, …   ┆ nay", "Ch ┆ River",  │
│           ┆           ┆ in 2015,  ┆ , "Maté's ┆   ┆ null]     ┆ null]     ┆ ardonnay" ┆ "Kumeu   │
│           ┆           ┆ bu…       ┆ Vi…       ┆   ┆           ┆           ┆ , ……      ┆ River",… │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Slovakia  ┆ [70992,   ┆ ["Slovaki ┆ [null,    ┆ … ┆ [null,    ┆ [null,    ┆ ["Rieslin ┆ ["Châtea │
│           ┆ 87878,    ┆ an        ┆ null,     ┆   ┆ null,     ┆ null,     ┆ g", "Ries ┆ u Bela", │
│           ┆ 143322]   ┆ winemaker ┆ null]     ┆   ┆ null]     ┆ null]     ┆ ling",    ┆ "Château │
│           ┆           ┆ Miroslav… ┆           ┆   ┆           ┆           ┆ "Ries…    ┆ Bela…    │
│ Czech     ┆ [72363,   ┆ ["Intense ┆ [null,    ┆ … ┆ [null,    ┆ [null,    ┆ ["Rivaner ┆ ["Vino z │
│ Republic  ┆ 73213, …  ┆ floral    ┆ null, …   ┆   ┆ null, …   ┆ null, …   ┆ ", "Pinot ┆ Czech",  │
│           ┆ 75015]    ┆ and       ┆ null]     ┆   ┆ null]     ┆ null]     ┆ Blanc", … ┆ "Vino z  │
│           ┆           ┆ yellow    ┆           ┆   ┆           ┆           ┆ "…        ┆ Czech…   │
│           ┆           ┆ pe…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ Egypt     ┆ [118982,  ┆ ["Ripe    ┆ ["Caspar  ┆ … ┆ [null,    ┆ [null,    ┆ ["Grenach ┆ ["Sahara │
│           ┆ 119008,   ┆ pear,     ┆ Blanc de  ┆   ┆ null,     ┆ null,     ┆ e",       ┆ Vineyard │
│           ┆ 119894]   ┆ apple and ┆ Noirs",   ┆   ┆ null]     ┆ null]     ┆ "Chenin   ┆ s",      │
│           ┆           ┆ tropica…  ┆ "Cas…     ┆   ┆           ┆           ┆ Blanc",   ┆ "Sahara  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ "…        ┆ V…       │
│ Tunisia   ┆ [138139,  ┆ ["An irre ┆ ["Selian  ┆ … ┆ [null,    ┆ [null,    ┆ ["Rosé",  ┆ ["Domain │
│           ┆ 139931]   ┆ sistible  ┆ Mystère", ┆   ┆ null]     ┆ null]     ┆ "White    ┆ e Neferi │
│           ┆           ┆ rosé from ┆ "Selian"] ┆   ┆           ┆           ┆ Blend"]   ┆ s",      │
│           ┆           ┆ Tu…       ┆           ┆   ┆           ┆           ┆           ┆ "Domaine │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ N…       │
│ US-France ┆ [144054]  ┆ ["Defies  ┆ [null]    ┆ … ┆ [null]    ┆ [null]    ┆ ["Viognie ┆ ["Deux   │
│           ┆           ┆ categoriz ┆           ┆   ┆           ┆           ┆ r"]       ┆ C"]      │
│           ┆           ┆ ation, in ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ mo…       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [218]:
preçomedio = wine.group_by("country").agg(pl.col("price").mean().alias("price-medio")).sort("price-medio", descending=True).drop_nulls("price-medio")
#estou agrupando
#calculando a média
#colocando dando um nome para a coluna da média
#colocando na ordem do maior para o menor

In [219]:
print(preçomedio) #US-France possui o maior preço na media

shape: (47, 2)
┌────────────────────────┬─────────────┐
│ country                ┆ price-medio │
│ ---                    ┆ ---         │
│ str                    ┆ f64         │
╞════════════════════════╪═════════════╡
│ US-France              ┆ 50.0        │
│ England                ┆ 47.5        │
│ France                 ┆ 45.619885   │
│ Hungary                ┆ 44.204348   │
│ Luxembourg             ┆ 40.666667   │
│ …                      ┆ …           │
│ Ukraine                ┆ 13.0        │
│ Bosnia and Herzegovina ┆ 12.75       │
│ Bulgaria               ┆ 11.545455   │
│ Lithuania              ┆ 10.0        │
│ Montenegro             ┆ 10.0        │
└────────────────────────┴─────────────┘

In [167]:
nova_wine.group_by("country").agg(pl.col("price").mean().alias("price-medio")).sort("price-medio", descending=True)
#só estou verificando no dataframe limpo, não a outros dados a não ser do US
#dutante a limpeza dos valores em branco, todos os outros paises foram esxluidos

shape: (1, 2)
┌─────────┬─────────────┐
│ country ┆ price-medio │
│ ---     ┆ ---         │
│ str     ┆ f64         │
╞═════════╪═════════════╡
│ US      ┆ 37.546316   │
└─────────┴─────────────┘

In [220]:
notamax = wine.group_by("variety").agg(pl.col("points").max().alias("points-max")).sort("points-max", descending=True)
#estou agrupando
#calculando a maxima
#colocando dando um nome para a coluna da maxima
#colocando na ordem do maior para o menor

In [221]:
print(notamax)

shape: (632, 2)
┌────────────────────────────┬────────────┐
│ variety                    ┆ points-max │
│ ---                        ┆ ---        │
│ str                        ┆ i64        │
╞════════════════════════════╪════════════╡
│ Syrah                      ┆ 100        │
│ Cabernet Blend             ┆ 100        │
│ Bordeaux-style White Blend ┆ 100        │
│ Red Blend                  ┆ 100        │
│ Muscat                     ┆ 100        │
│ …                          ┆ …          │
│ Rufete                     ┆ 82         │
│ Aidani                     ┆ 82         │
│ Chardonelle                ┆ 82         │
│ Malvar                     ┆ 81         │
│ Parraleta                  ┆ 80         │
└────────────────────────────┴────────────┘

In [207]:
nota_chardonnay = (wine.filter(pl.col("variety") == "Chardonnay").group_by("variety").agg(pl.col("points").max().alias("points-max"))
)
#estou filtrando por variedade por grupo e nota maxima

In [213]:
print(nota_chardonnay)

shape: (1, 2)
┌────────────┬────────────┐
│ variety    ┆ points-max │
│ ---        ┆ ---        │
│ str        ┆ i64        │
╞════════════╪════════════╡
│ Chardonnay ┆ 100        │
└────────────┴────────────┘

In [214]:
pontuações_chardonnays = (wine.filter(pl.col("variety") == "Chardonnay").filter(pl.col("points") == pl.col("points").max()))
#aqui estou filtrando e calculando os valores de todo o dataset, trazendo o país, a notra e o valor

In [215]:
print(pontuações_chardonnays['country','points', 'price'])

shape: (3, 3)
┌─────────┬────────┬────────┐
│ country ┆ points ┆ price  │
│ ---     ┆ ---    ┆ ---    │
│ str     ┆ i64    ┆ f64    │
╞═════════╪════════╪════════╡
│ France  ┆ 100    ┆ 1400.0 │
│ France  ┆ 100    ┆ 1400.0 │
│ France  ┆ 100    ┆ 1400.0 │
└─────────┴────────┴────────┘

In [216]:
precos_medios = (wine.group_by("variety").agg(pl.col("price").mean().alias("preco_medio")).sort("preco_medio", descending=True)).drop_nulls("preco_medio")
#aqui estou filtrando e calculando os valores de todo o dataset e tirando os valores vazios

In [212]:
print(precos_medios)

shape: (619, 2)
┌─────────────────────────────────┬─────────────┐
│ variety                         ┆ preco_medio │
│ ---                             ┆ ---         │
│ str                             ┆ f64         │
╞═════════════════════════════════╪═════════════╡
│ Cabernet-Shiraz                 ┆ 150.0       │
│ Muscadel                        ┆ 141.3       │
│ Mazuelo                         ┆ 98.5        │
│ Tinto Fino                      ┆ 83.12       │
│ Mission                         ┆ 82.571429   │
│ …                               ┆ …           │
│ Viura-Chardonnay                ┆ 8.727273    │
│ Pigato                          ┆ 8.0         │
│ Cabernet Sauvignon and Tinta R… ┆ 8.0         │
│ Carineña                        ┆ 8.0         │
│ Macabeo-Moscatel                ┆ 7.333333    │
└─────────────────────────────────┴─────────────┘

In [226]:
wine = wine.with_columns((pl.col("points") / pl.col("price")).alias("custo-beneficio"))
# aqui estou criando a coluna com with_columns()
# já passando o argumento que sera points/price

In [227]:
print(wine['points', 'price', 'custo-beneficio'])

shape: (150_930, 3)
┌────────┬───────┬─────────────────┐
│ points ┆ price ┆ custo-beneficio │
│ ---    ┆ ---   ┆ ---             │
│ i64    ┆ f64   ┆ f64             │
╞════════╪═══════╪═════════════════╡
│ 96     ┆ 235.0 ┆ 0.408511        │
│ 96     ┆ 110.0 ┆ 0.872727        │
│ 96     ┆ 90.0  ┆ 1.066667        │
│ 96     ┆ 65.0  ┆ 1.476923        │
│ 95     ┆ 66.0  ┆ 1.439394        │
│ …      ┆ …     ┆ …               │
│ 91     ┆ 20.0  ┆ 4.55            │
│ 91     ┆ 27.0  ┆ 3.37037         │
│ 91     ┆ 20.0  ┆ 4.55            │
│ 90     ┆ 52.0  ┆ 1.730769        │
│ 90     ┆ 15.0  ┆ 6.0             │
└────────┴───────┴─────────────────┘